# Generated by Django 3.2.9 on 2022-03-06 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_addtocart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
