# Generated by Django 3.2.9 on 2022-03-06 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20220306_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='books',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
