# Generated by Django 3.2.9 on 2022-03-06 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_checkout_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
