# Generated by Django 3.2.9 on 2022-03-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_checkout_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='books',
            field=models.JSONField(null=True),
        ),
    ]
